#!/usr/bin/env python

import sys
import fileinput
import argparse
from uritemplate import expand, variables

parser = argparse.ArgumentParser()
parser.add_argument('template', help="URI Template to use")
parser.add_argument('-i','--input', type=argparse.FileType('r'),
  help="Input", default=sys.stdin)
parser.add_argument("-d","--delimiter", default=" ", help="Delimiter to split on")
args = parser.parse_args()

for line in args.input:
  print expand(args.template, dict(zip(variables(args.template),line.rstrip().split(args.delimiter)))) 
