#!/usr/bin/env python
import sys
from urlparse import urljoin
from optparse import OptionParser

parser = OptionParser()

(options, args) = parser.parse_args()
if len(args) == 2:
  print urljoin(args[0],args[1])
else:
  print urljoin(args[0]," ".join(sys.stdin).rstrip())
